FROM apache/spark:3.5.0

# Chuyển sang root để cài package
USER root

RUN apt-get update && apt-get install -y python3-pip curl \
    && pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir pyyaml requests kafka-python python-dotenv

# ===============================
# DOWNLOAD REQUIRED JARS
# ===============================

# ===============================
# Kafka dependencies
# ===============================

RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar \
 && curl -L -o /opt/spark/jars/kafka-clients-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar \
 && curl -L -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar \
 && curl -L -o /opt/spark/jars/commons-pool2-2.11.1.jar \
    https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

# ✅ PostgreSQL JDBC DRIVER
RUN curl -L -o /opt/spark/jars/postgresql-42.6.0.jar \
    https://repo1.maven.org/maven2/org/postgresql/postgresql/42.6.0/postgresql-42.6.0.jar

# ===============================
# MinIO / S3A dependencies
# ===============================
RUN curl -L -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
 && curl -L -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar


# Quay lại user spark
USER spark

WORKDIR /opt/project

COPY . /opt/project

ENV PYTHONPATH=/opt/project/src:$PYTHONPATH
ENV PYTHONUNBUFFERED=1

CMD ["bash"]
