FROM apache/spark:3.5.0

# Chuyển sang root để cài package
USER root

RUN apt-get update && apt-get install -y python3-pip \
    && pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir pyyaml requests kafka-python python-dotenv

# Tải JAR từ Maven repository

# Tải Kafka connector và kafka-clients
RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar \
 && curl -L -o /opt/spark/jars/kafka-clients-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar \
 && curl -L -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar

# Quay lại user spark
USER spark

WORKDIR /opt/project

# Copy project
COPY . /opt/project

# PYTHONPATH cho spark worker
ENV PYTHONPATH=/opt/project/src:$PYTHONPATH
ENV PYTHONUNBUFFERED=1

# Command mặc định
CMD ["bash"]
